version: '3.3'
services:
  mysql-linqproject:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'linqproject'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'lp'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'linqproject'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'linqproject'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - linqproject:/var/lib/mysql
# Names our volume
volumes:
  linqproject: